### ISSUE TITLE
how to read csv

### ISSUE THREAD

**Issue by martino-vic** [dictionaria/pydictionaria#27]
Hello everbody,

I need to convert some of my [csv-data](https://github.com/martino-vic/streitberggothic/issues/8) to a dictionary. Which function do I have to use in the conversion script to read csv-files? There doesn't seem to a be a documentation, and in the examples so far, I can only find functions that handle sfm-files. Thank you very much in advance for the help!

**Comment by johenglisch** [comment]
Hi!

Unfortunately, there isn't a ready-made function for this -- pydictionaria was made with the SFM format in mind because that's what most submissions used.  What we did in cases like Media Lengua was converting the tabular data (excel in that case) to SFM in the `cldfbench download` step and then use `pydictionaria` to create the cldf (the conversion function was always custom-made because no two excel tables were ever the same):

https://github.com/dictionaria/medialengua/blob/main/cldfbench_medialengua.py#L141-L147

But that workflow is mostly a carry-over from the pre-CLDFbench days.

Nowadays, I would just read the CSV data via `self.raw_dir.read_csv` and make the EntryTable and SenseTable manually (which usually isn't all that hard).  From there you can call into pydictionaria for CLDF data creation, further validation, etc. if you like.  Basically like in the second half of `makecldf` here:

https://github.com/dictionaria/medialengua/blob/main/cldfbench_medialengua.py#L200-L240

Sry if pydictionaria isn't more flexible -- it has grown into like three entirely different things over the years and carries some of the jank of previous iterations with it.

Johannes

**Comment by martino-vic** [comment]
Thank you so much for the overview, I will play around with this and see if I can make it work, but it does look very promising indeed :)
